apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-application-deployment
spec:
  selector:
    matchLabels:
      app: devops-application
  template:
    metadata:
      labels:
        app: devops-application
    spec:
      containers:
        - name: devops-application
          image: emreeoozell/devops-application-002:v003
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devops-application-service
spec:
  selector:
    app: devops-application
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort